[package]
name = "kata-59e19a747905df23cb000024"
version = "0.1.0"
authors = ["Maki <mxmcube@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
