[package]
name = "kata-58aed2cafab8faca1d000e20"
version = "0.1.0"
authors = ["Maki <mxmcube@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
